# Site settings
title: Vncz's blog
email: vincenz.chianese@yahoo.it
description: > # this means to ignore newlines until "baseurl:"
  Home of Vincenzo Chianese.
  Let's talk about programming.
  Thoughts, stories and ideas of a (failed) developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vncz.js.org" # the base hostname & protocol for your site
twitter_username: d3dvincent
github_username:  XVincentX

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
