# Site wide configuration

title:            "Vncz's Blog"
locale:           en_US


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Site owner
owner:
  name: Vincenzo Chianese
  avatar: https://i.imgur.com/zCLOHPB.jpg
  bio: "Let's talk about programming. Thoughts, stories and ideas of a (failed) developer."
  email: vincenz.chianese@icloud.com
  disqus-shortname: XVincentX
  twitter: D3DVincent
  facebook: D3DVincent
  google:
    plus: #username
    analytics: UA-64721010-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: XVincentX
  stackoverflow: 1044264/vincenzo
  linkedin: d3dvincent
  codepen: XVincentX
  xing: #username
  instagram: vincenzo_chianese
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: vincenzo-chianese-1
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
