# Site wide configuration

title:            "Vncz's Blog"
locale:           en_US


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Vincenzo Chianese
  avatar: https://scontent.xx.fbcdn.net/hphotos-xat1/v/l/t1.0-9/12122842_10154298421326040_2722584820849236967_n.jpg?oh=8c244e4b7d601cf16db2c37b05a234d9&oe=56BE1864
  bio: "Let's talk about programming. Thoughts, stories and ideas of a (failed) developer."
  email: vincenz.chianese@yahoo.it
  disqus-shortname: XVincentX
  twitter: D3DVincent
  facebook: D3DVincent
  google:
    plus: #username
    analytics: UA-64721010-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: XVincentX
  stackoverflow: 1044264/vincenzo
  linkedin: d3dvincent
  xing: #username
  instagram: vincenzo_chianese
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: vincenzo-chianese-1
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
